name: CodeRunner Deploy

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project name (e.g. my-awesome-app)'
        required: true
      code:
        description: 'Paste your code here'
        required: true
      filename:
        description: 'What to name the file (e.g. index.html)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write code to file
        run: echo "${{ github.event.inputs.code }}" > ${{ github.event.inputs.filename }}

      - name: Commit and push file
        run: |
          git config user.email "coderunner@github.com"
          git config user.name "CodeRunner"
          git add .
          git commit -m "CodeRunner deploy: ${{ github.event.inputs.projectName }}"
          git push

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --name=${{ github.event.inputs.projectName }} --token=${{ secrets.VERCEL_TOKEN }}
